tgt2det_min_threshold: -0.13
null_target_weight: 1
learning_rate: 0.0001
allow_reflection: true
lr_scheduler_params:
  type: StepLR
  step_size: 100
  gamma: 0.1
assignment_threshold: -0.1
assignment_metric: ulbr1
