accelerator: gpu
devices: 1
accumulate_grad_batches: 64
max_epochs: 150
check_val_every_n_epoch: 5
workdir: ???
callbacks:
  - type: model_checkpoint
    save_on_train_epoch_end: false
    save_top_k: 3
    save_last: true
    mode: max
    monitor: val_COMBINED_MOTA
    dirpath: ${trainer.workdir}/ckpts
logger:
  type: tensorboard
  save_dir: ${trainer.workdir}/logs
